version: '3'
services:
  ztiback:
    image: amazoncorretto:17.0.0-alpine
    ports:
      - 8088:8088
    volumes:
      - ./ZTI_Proj/target/ZTI_Proj-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: java -jar /app/app.jar